package:
  name: prefersim
  version: "1.0"

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - gsl

  run:
    - gsl

source:
  url: https://github.com/LohmuellerLab/PReFerSim/releases/download/1.0/prefersimv1.0.tar.gz
  md5: 2dff98c4d67cd9a5c46e9f503b41529e

test:
  commands:
    - prefersim

about:
  home:  'https://github.com/LohmuellerLab/PReFerSim'
  license: Unknown
  summary: Fast simulation of demography and selection under the Poisson Random Field model

extra:
  identifiers:
    - doi:https://doi.org/10.1093/bioinformatics/btw478

